import React from "react";
import {
    AlbumFillIcon,
    AlbumIcon,
    AlignCenterIcon,
    AlignJustifyIcon,
    AlignLeftIcon,
    AlignRightIcon,
    ArrowDownCircleFillIcon,
    ArrowDownCircleIcon,
    ArrowDownCloudFillIcon,
    ArrowDownCloudIcon,
    ArrowDownIcon,
    ArrowLeftCircleFillIcon,
    ArrowLeftCircleIcon,
    ArrowLeftDownIcon,
    ArrowLeftIcon,
    ArrowLeftUpIcon,
    ArrowRightCircleFillIcon,
    ArrowRightCircleIcon,
    ArrowRightDownIcon,
    ArrowRightIcon,
    ArrowRightUpIcon,
    ArrowUpCircleFillIcon,
    ArrowUpCircleIcon,
    ArrowUpCloudFillIcon,
    ArrowUpCloudIcon,
    ArrowUpIcon,
    BinFillIcon,
    BinIcon,
    BookmarkFillIcon,
    BookmarkIcon,
    CalendarCrossFillIcon,
    CalendarCrossIcon,
    CalendarDotFillIcon,
    CalendarDotIcon,
    CalendarEventFillIcon,
    CalendarEventIcon,
    CalendarFillIcon,
    CalendarIcon,
    CalendarPlusFillIcon,
    CalendarPlusIcon,
    CalendarTickFillIcon,
    CalendarTickIcon,
    CameraFillIcon,
    CameraIcon,
    CaretDownIcon,
    CaretLeftIcon,
    CaretRightIcon,
    CaretUpIcon,
    Chevron2LeftIcon,
    Chevron2RightIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronLineLeftIcon,
    ChevronLineRightIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    CircleIcon,
    ClockFillIcon,
    ClockIcon,
    CloudFillIcon,
    CloudIcon,
    CrossCircleFillIcon,
    CrossCircleIcon,
    CrossIcon,
    DocFillIcon,
    DocIcon,
    DocPencilFillIcon,
    DocPencilIcon,
    DollarIcon,
    DotCircleIcon,
    DownloadIcon,
    EllipsisHorizontalIcon,
    EllipsisVerticalIcon,
    EnvelopeFillIcon,
    EnvelopeIcon,
    EnvelopeOpenFillIcon,
    EnvelopeOpenIcon,
    ExclamationCircleFillIcon,
    ExclamationCircleIcon,
    ExclamationTriangleFillIcon,
    ExclamationTriangleIcon,
    ExternalIcon,
    EyeFillIcon,
    EyeIcon,
    EyeSlashFillIcon,
    EyeSlashIcon,
    FilterIcon,
    GearFillIcon,
    GearIcon,
    GlobeIcon,
    ICircleFillIcon,
    ICircleIcon,
    InboxFillIcon,
    InboxIcon,
    LanguageIcon,
    LightbulbFillIcon,
    LightbulbIcon,
    LinkIcon,
    ListIcon,
    LockFillIcon,
    LockIcon,
    LoginIcon,
    LogoutIcon,
    MagnifierIcon,
    MagnifierMinusIcon,
    MagnifierPlusIcon,
    MapFillIcon,
    MapIcon,
    MenuIcon,
    MinusCircleFillIcon,
    MinusCircleIcon,
    MinusIcon,
    NavigationFillIcon,
    NavigationIcon,
    NonRecurringIcon,
    PencilFillIcon,
    PencilIcon,
    PencilStrokeFillIcon,
    PencilStrokeIcon,
    Person2FillIcon,
    Person2Icon,
    Person2MinusFillIcon,
    Person2MinusIcon,
    Person2PlusFillIcon,
    Person2PlusIcon,
    PersonFillIcon,
    PersonGearFillIcon,
    PersonGearIcon,
    PersonGroupFillIcon,
    PersonGroupIcon,
    PersonIcon,
    PersonMinusFillIcon,
    PersonMinusIcon,
    PersonPlusFillIcon,
    PersonPlusIcon,
    PhoneFillIcon,
    PhoneIcon,
    PinFillIcon,
    PinIcon,
    PlaceholderIcon,
    PlaceholderImageIcon,
    PlusCircleFillIcon,
    PlusCircleIcon,
    PlusIcon,
    PointIcon,
    PrinterFillIcon,
    PrinterIcon,
    QrIcon,
    QuestionmarkCircleFillIcon,
    QuestionmarkCircleIcon,
    RecurringIcon,
    RefreshIcon,
    ReplayIcon,
    RetryIcon,
    ReturnIcon,
    ShareIcon,
    SortAscendingIcon,
    SortDescendingIcon,
    Square2x2FillIcon,
    Square2x2Icon,
    SquareIcon,
    StarFillIcon,
    StarIcon,
    TextFillIcon,
    TextIcon,
    TickCircleFillIcon,
    TickCircleIcon,
    TickCloudFillIcon,
    TickCloudIcon,
    TickIcon,
    TickSquareFillIcon,
    TickSquareIcon,
    TicketFillIcon,
    TicketIcon,
    ToggleOffFillIcon,
    ToggleOffIcon,
    ToggleOnFillIcon,
    ToggleOnIcon,
    TriangleForwardFillIcon,
    TriangleForwardIcon,
    UploadIcon,
} from "../../src";

export const ICONS: JSX.Element[] = [
    // =============================================================================
    // SHAPES
    // =============================================================================
    // Arrow
    <ArrowDownIcon key="ArrowDownIcon" />,
    <ArrowLeftDownIcon key="ArrowLeftDownIcon" />,
    <ArrowLeftUpIcon key="ArrowLeftUpIcon" />,
    <ArrowLeftIcon key="ArrowLeftIcon" />,
    <ArrowRightDownIcon key="ArrowRightDownIcon" />,
    <ArrowRightUpIcon key="ArrowRightUpIcon" />,
    <ArrowRightIcon key="ArrowRightIcon" />,
    <ArrowUpIcon key="ArrowUpIcon" />,
    // Arrow Circle
    <ArrowDownCircleIcon key="ArrowDownCircleIcon" />,
    <ArrowLeftCircleIcon key="ArrowLeftCircleIcon" />,
    <ArrowRightCircleIcon key="ArrowRightCircleIcon" />,
    <ArrowUpCircleIcon key="ArrowUpCircleIcon" />,
    <ArrowDownCircleFillIcon key="ArrowDownCircleFillIcon" />,
    <ArrowLeftCircleFillIcon key="ArrowLeftCircleFillIcon" />,
    <ArrowRightCircleFillIcon key="ArrowRightCircleFillIcon" />,
    <ArrowUpCircleFillIcon key="ArrowUpCircleFillIcon" />,
    // Chevron
    <ChevronDownIcon key="ChevronDownIcon" />,
    <ChevronLeftIcon key="ChevronLeftIcon" />,
    <ChevronRightIcon key="ChevronRightIcon" />,
    <ChevronUpIcon key="ChevronUpIcon" />,
    // Chevron
    <ChevronLineLeftIcon key="ChevronLineLeftIcon" />,
    <ChevronLineRightIcon key="ChevronLineRightIcon" />,
    <Chevron2LeftIcon key="Chevron2LeftIcon" />,
    <Chevron2RightIcon key="Chevron2RightIcon" />,
    // Caret
    <CaretLeftIcon key="CaretLeftIcon" />,
    <CaretRightIcon key="CaretRightIcon" />,
    <CaretUpIcon key="CaretUpIcon" />,
    <CaretDownIcon key="CaretDownIcon" />,
    // Triangle
    <TriangleForwardIcon key="TriangleForwardIcon" />,
    <TriangleForwardFillIcon key="TriangleForwardFillIcon" />,
    // Ellipsis
    <EllipsisHorizontalIcon key="EllipsisHorizontalIcon" />,
    <EllipsisVerticalIcon key="EllipsisVerticalIcon" />,
    // Plus
    <PlusIcon key="PlusIcon" />,
    <PlusCircleIcon key="PlusCircleIcon" />,
    <PlusCircleFillIcon key="PlusCircleFillIcon" />,
    // Minus
    <MinusIcon key="MinusIcon" />,
    <MinusCircleIcon key="MinusCircleIcon" />,
    <MinusCircleFillIcon key="MinusCircleFillIcon" />,
    // Cross
    <CrossIcon key="CrossIcon" />,
    <CrossCircleIcon key="CrossCircleIcon" />,
    <CrossCircleFillIcon key="CrossCircleFillIcon" />,
    // Tick
    <TickIcon key="TickIcon" />,
    <TickCircleIcon key="TickCircleIcon" />,
    <TickCircleFillIcon key="TickCircleFillIcon" />,
    // Exclamation
    <ExclamationCircleIcon key="ExclamationCircleIcon" />,
    <ExclamationCircleFillIcon key="ExclamationCircleFillIcon" />,
    <ExclamationTriangleIcon key="ExclamationTriangleIcon" />,
    <ExclamationTriangleFillIcon key="ExclamationTriangleFillIcon" />,
    // QuestionMark
    <QuestionmarkCircleIcon key="QuestionmarkCircleIcon" />,
    <QuestionmarkCircleFillIcon key="QuestionmarkCircleFillIcon" />,
    // Circle
    <CircleIcon key="CircleIcon" />,
    <DotCircleIcon key="DotCircleIcon" />,
    // I-Circle
    <ICircleIcon key="ICircleIcon" />,
    <ICircleFillIcon key="ICircleFillIcon" />,
    // Square
    <SquareIcon key="SquareIcon" />,
    <TickSquareIcon key="TickSquareIcon" />,
    <TickSquareFillIcon key="TickSquareFillIcon" />,
    <Square2x2Icon key="Square2x2Icon" />,
    <Square2x2FillIcon key="Square2x2FillIcon" />,
    // Cloud
    <CloudIcon key="CloudIcon" />,
    <CloudFillIcon key="CloudFillIcon" />,
    <ArrowUpCloudIcon key="ArrowUpCloudIcon" />,
    <ArrowUpCloudFillIcon key="ArrowUpCloudFillIcon" />,
    <ArrowDownCloudIcon key="ArrowDownCloudIcon" />,
    <ArrowDownCloudFillIcon key="ArrowDownCloudFillIcon" />,
    <TickCloudIcon key="TickCloudIcon" />,
    <TickCloudFillIcon key="TickCloudFillIcon" />,
    // Dollar
    <DollarIcon key="DollarIcon" />,

    // =============================================================================
    // OBJECTS
    // =============================================================================
    // Evelope
    <EnvelopeIcon key="EnvelopeIcon" />,
    <EnvelopeFillIcon key="EnvelopeFillIcon" />,
    <EnvelopeOpenIcon key="EnvelopeOpenIcon" />,
    <EnvelopeOpenFillIcon key="EnvelopeOpenFillIcon" />,
    // Bookmark
    <BookmarkIcon key="BookmarkIcon" />,
    <BookmarkFillIcon key="BookmarkFillIcon" />,
    // Doc
    <DocIcon key="DocIcon" />,
    <DocFillIcon key="DocFillIcon" />,
    <DocPencilIcon key="DocPencilIcon" />,
    <DocPencilFillIcon key="DocPencilFillIcon" />,
    // Pencil
    <PencilIcon key="PencilIcon" />,
    <PencilFillIcon key="PencilFillIcon" />,
    <PencilStrokeIcon key="PencilStrokeIcon" />,
    <PencilStrokeFillIcon key="PencilStrokeFillIcon" />,
    // Ticket
    <TicketIcon key="TicketIcon" />,
    <TicketFillIcon key="TicketFillIcon" />,
    // Map
    <MapIcon key="MapIcon" />,
    <MapFillIcon key="MapFillIcon" />,
    // Lightbulb
    <LightbulbIcon key="LightbulbIcon" />,
    <LightbulbFillIcon key="LightbulbFillIcon" />,
    // Clock
    <ClockIcon key="ClockIcon" />,
    <ClockFillIcon key="ClockFillIcon" />,
    // Navigation
    <NavigationIcon key="NavigationIcon" />,
    <NavigationFillIcon key="NavigationFillIcon" />,
    // Star
    <StarIcon key="StarIcon" />,
    <StarFillIcon key="StarFillIcon" />,
    // Printer
    <PrinterIcon key="PrinterIcon" />,
    <PrinterFillIcon key="PrinterFillIcon" />,
    // Phone
    <PhoneIcon key="PhoneIcon" />,
    <PhoneFillIcon key="PhoneFillIcon" />,
    // Gear
    <GearIcon key="GearIcon" />,
    <GearFillIcon key="GearFillIcon" />,
    // Inbox
    <InboxIcon key="InboxIcon" />,
    <InboxFillIcon key="InboxFillIcon" />,
    // Pin
    <PinIcon key="PinIcon" />,
    <PinFillIcon key="PinFillIcon" />,
    // Text
    <TextIcon key="TextIcon" />,
    <TextFillIcon key="TextFillIcon" />,
    // Bin
    <BinIcon key="BinIcon" />,
    <BinFillIcon key="BinFillIcon" />,
    // Camera
    <CameraIcon key="CameraIcon" />,
    <CameraFillIcon key="CameraFillIcon" />,
    // Lock
    <LockIcon key="LockIcon" />,
    <LockFillIcon key="LockFillIcon" />,
    // Eye
    <EyeIcon key="EyeIcon" />,
    <EyeFillIcon key="EyeFillIcon" />,
    <EyeSlashIcon key="EyeSlashIcon" />,
    <EyeSlashFillIcon key="EyeSlashFillIcon" />,
    // Person
    <PersonIcon key="PersonIcon" />,
    <PersonFillIcon key="PersonFillIcon" />,
    <PersonPlusIcon key="PersonPlusIcon" />,
    <PersonPlusFillIcon key="PersonPlusFillIcon" />,
    <PersonMinusIcon key="PersonMinusIcon" />,
    <PersonMinusFillIcon key="PersonMinusFillIcon" />,
    <PersonGearIcon key="PersonGearIcon" />,
    <PersonGearFillIcon key="PersonGearFillIcon" />,
    <PersonGroupIcon key="PersonGroupIcon" />,
    <PersonGroupFillIcon key="PersonGroupFillIcon" />,
    <Person2Icon key="Person2Icon" />,
    <Person2FillIcon key="Person2FillIcon" />,
    <Person2PlusIcon key="Person2PlusIcon" />,
    <Person2PlusFillIcon key="Person2PlusFillIcon" />,
    <Person2MinusIcon key="Person2MinusIcon" />,
    <Person2MinusFillIcon key="Person2MinusFillIcon" />,
    // Toggle
    <ToggleOffIcon key="ToggleOffIcon" />,
    <ToggleOffFillIcon key="ToggleOffFillIcon" />,
    <ToggleOnIcon key="ToggleOnIcon" />,
    <ToggleOnFillIcon key="ToggleOnFillIcon" />,
    // Calendar
    <CalendarIcon key="CalendarIcon" />,
    <CalendarFillIcon key="CalendarFillIcon" />,
    <CalendarEventIcon key="CalendarEventIcon" />,
    <CalendarEventFillIcon key="CalendarEventFillIcon" />,
    <CalendarPlusIcon key="CalendarPlusIcon" />,
    <CalendarPlusFillIcon key="CalendarPlusFillIcon" />,
    <CalendarTickIcon key="CalendarTickIcon" />,
    <CalendarTickFillIcon key="CalendarTickFillIcon" />,
    <CalendarCrossIcon key="CalendarCrossIcon" />,
    <CalendarCrossFillIcon key="CalendarCrossFillIcon" />,
    <CalendarDotIcon key="CalendarDotIcon" />,
    <CalendarDotFillIcon key="CalendarDotFillIcon" />,
    // Album
    <AlbumIcon key="AlbumIcon" />,
    <AlbumFillIcon key="AlbumFillIcon" />,
    // Magnifier
    <MagnifierIcon key="MagnifierIcon" />,
    <MagnifierPlusIcon key="MagnifierPlusIcon" />,
    <MagnifierMinusIcon key="MagnifierMinusIcon" />,
    // Menu
    <MenuIcon key="MenuIcon" />,
    // Language
    <LanguageIcon key="LanguageIcon" />,
    // Globe
    <GlobeIcon key="GlobeIcon" />,
    // Qr
    <QrIcon key="QrIcon" />,

    // =============================================================================
    // MISC
    // =============================================================================
    // Align
    <AlignLeftIcon key="AlignLeftIcon" />,
    <AlignCenterIcon key="AlignCenterIcon" />,
    <AlignRightIcon key="AlignRightIcon" />,
    <AlignJustifyIcon key="AlignJustifyIcon" />,
    // Sort
    <SortDescendingIcon key="SortDescendingIcon" />,
    <SortAscendingIcon key="SortAscendingIcon" />,
    // List
    <ListIcon key="ListIcon" />,
    // Filter
    <FilterIcon key="FilterIcon" />,
    // Link
    <LinkIcon key="LinkIcon" />,
    // External
    <ExternalIcon key="ExternalIcon" />,
    // Logout
    <LogoutIcon key="LogoutIcon" />,
    // Login
    <LoginIcon key="LoginIcon" />,
    // Upload
    <UploadIcon key="UploadIcon" />,
    // Download
    <DownloadIcon key="DownloadIcon" />,
    // Share
    <ShareIcon key="ShareIcon" />,
    // Recurring
    <RecurringIcon key="RecurringIcon" />,
    // NonRecurring
    <NonRecurringIcon key="NonRecurringIcon" />,
    // Refresh
    <RefreshIcon key="RefreshIcon" />,
    // Replay
    <ReplayIcon key="ReplayIcon" />,
    // Retry
    <RetryIcon key="RetryIcon" />,
    // Return
    <ReturnIcon key="ReturnIcon" />,

    // =============================================================================
    // FIGMA EXCLUSIVE
    // =============================================================================
    // Point
    <PointIcon key="PointIcon" />,
    // Placeholder
    <PlaceholderImageIcon key="PlaceholderImageIcon" />,
    <PlaceholderIcon key="PlaceholderIcon" />,
];
