import React from "react";
import {
    ArrowDownCircleFillIcon,
    ArrowDownCircleIcon,
    ArrowDownIcon,
    ArrowLeftCircleFillIcon,
    ArrowLeftCircleIcon,
    ArrowLeftDownIcon,
    ArrowLeftIcon,
    ArrowLeftUpIcon,
    ArrowRightCircleFillIcon,
    ArrowRightCircleIcon,
    ArrowRightDownIcon,
    ArrowRightIcon,
    ArrowRightUpIcon,
    ArrowUpCircleFillIcon,
    ArrowUpCircleIcon,
    ArrowUpIcon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronLineLeftIcon,
    ChevronLineRightIcon,
    ChevronRightIcon,
    ChevronUpIcon,
} from "../../src";

export const ICONS: JSX.Element[] = [
    <ArrowDownIcon key="ArrowDownIcon" />,
    <ArrowLeftDownIcon key="ArrowLeftDownIcon" />,
    <ArrowLeftUpIcon key="ArrowLeftUpIcon" />,
    <ArrowLeftIcon key="ArrowLeftIcon" />,
    <ArrowRightDownIcon key="ArrowRightDownIcon" />,
    <ArrowRightUpIcon key="ArrowRightUpIcon" />,
    <ArrowRightIcon key="ArrowRightIcon" />,
    <ArrowUpIcon key="ArrowUpIcon" />,
    // Arrow Down Circle
    <ArrowDownCircleIcon key="ArrowDownCircleIcon" />,
    <ArrowLeftCircleIcon key="ArrowLeftCircleIcon" />,
    <ArrowRightCircleIcon key="ArrowRightCircleIcon" />,
    <ArrowUpCircleIcon key="ArrowUpCircleIcon" />,
    <ArrowDownCircleFillIcon key="ArrowDownCircleFillIcon" />,
    <ArrowLeftCircleFillIcon key="ArrowLeftCircleFillIcon" />,
    <ArrowRightCircleFillIcon key="ArrowRightCircleFillIcon" />,
    <ArrowUpCircleFillIcon key="ArrowUpCircleFillIcon" />,
    // Chevron
    <ChevronDownIcon key="ChevronDownIcon" />,
    <ChevronLeftIcon key="ChevronLeftIcon" />,
    <ChevronRightIcon key="ChevronRightIcon" />,
    <ChevronUpIcon key="ChevronUpIcon" />,
    // Chevron Line
    <ChevronLineLeftIcon key="ChevronLineLeftIcon" />,
    <ChevronLineRightIcon key="ChevronLineRightIcon" />,
];
