# =================================
# Stage: build
# =================================

build-job:
    stage: build
    artifacts:
        paths:
            - "dist/*.tgz"
            - "$CI_PROJECT_DIR/storybook-static"
    allow_failure: false
    script:
        - |
            pushd $CI_PROJECT_DIR
            npm run build

            pushd dist
            npm pack

            pushd $CI_PROJECT_DIR
            npm run build-storybook
