# =================================
# Stage: install
# =================================

install-job:
    extends: .npm-install
    stage: install
    allow_failure: false
    script:
        - |
            # [ Check installation ]
            echo "installed packages:  $(ls -l node_modules | wc -l)"
