# =================================
# Stage: tag
# =================================

git-tag-release-job:
    extends: .git-tag-release
    stage: tag
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
